Improve PHP version requirement to ^7.1 || ~8.0.0 || ~8.1.0
cocur/slugify pull request #301
Opened 2022-01-15 09:05 UTC by florianeckerstorfer

This [came up in the comments](https://github.com/cocur/slugify/pull/299#discussion_r785034646) to a recently closed PR and I would appreciate your input on this.

2022-01-15 09:07 UTC, florianeckerstorfer commented
Added PHP 8.2.x to version range, since the unit tests are currently passing for it

2022-01-15 13:17 UTC, Ocramius requested changes
Note: you may want to run `composer update --lock`

2022-01-15 13:17 UTC, Ocramius commented on composer.json
> +        "php": "^7.1 || ~8.0.0 || ~8.1.0 || ~8.2.0",
Careful with `8.2.0`: I suggest holding off until it reaches RC, around october 2022.

Until then, any BC break is still possible.

2022-01-15 15:20 UTC, Ocramius commented
Remember `composer.lock`

2022-08-13 10:36 UTC, closed without merging

2022-08-13 10:39 UTC, Ocramius commented
@florianeckerstorfer is this closed on purpose?

2022-08-13 10:43 UTC, florianeckerstorfer commented
@Ocramius Yes, it took a long while, but I followed your suggestion and excluded 8.2 for now. Merged #313 instead